// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Detalle de la villa",
                            FechaActualizacion = new DateTime(2023, 10, 18, 17, 35, 10, 439, DateTimeKind.Local).AddTicks(3523),
                            FechaCreacion = new DateTime(2023, 10, 18, 17, 35, 10, 439, DateTimeKind.Local).AddTicks(3513),
                            ImageUrl = "",
                            MetrosCuadrados = 345,
                            Nombre = "Villa Real",
                            Ocupantes = 4,
                            Tarifa = 1313.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Detalle de la villa",
                            FechaActualizacion = new DateTime(2023, 10, 18, 17, 35, 10, 439, DateTimeKind.Local).AddTicks(3525),
                            FechaCreacion = new DateTime(2023, 10, 18, 17, 35, 10, 439, DateTimeKind.Local).AddTicks(3525),
                            ImageUrl = "",
                            MetrosCuadrados = 345,
                            Nombre = "Villa Real II",
                            Ocupantes = 4,
                            Tarifa = 1313.0
                        },
                        new
                        {
                            Id = 3,
                            Amenidad = "",
                            Detalle = "Detalle de la villa",
                            FechaActualizacion = new DateTime(2023, 10, 18, 17, 35, 10, 439, DateTimeKind.Local).AddTicks(3527),
                            FechaCreacion = new DateTime(2023, 10, 18, 17, 35, 10, 439, DateTimeKind.Local).AddTicks(3527),
                            ImageUrl = "",
                            MetrosCuadrados = 345,
                            Nombre = "Villa Real",
                            Ocupantes = 4,
                            Tarifa = 1313.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
